version: "3.7"

services:
  nginx-ssl:
    image: nginx:latest
    container_name: nginx-ssl
    labels:
      io.portainer.accesscontrol.teams: /certh
    ports:
      - "80:80"    # Changed from 5173 for HTTP
      - "443:443"  # Added HTTPS port
    restart: unless-stopped
    volumes:
      - ./distVDockerHarbor4:/var/www/html
      - ./nginx/templates:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot  # Added for ACME challenges
    networks:
      - ceasefire-test-backend-dev_alerts

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.teams: /certh
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./letsencrypt:/etc/letsencrypt-host 
      - ./certbot/data:/var/www/certbot  # Added for ACME challenges
    depends_on:
      - nginx-ssl
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email kostisfl@iti.gr --agree-tos --no-eff-email
             -d cyberpatrol-pilots.ceasefire-project.eu 
             -d www.cyberpatrol-pilots.ceasefire-project.eu
             --rsa-key-size 4096
             --key-type rsa
             --post-hook "mkdir -p /etc/letsencrypt; cp -r /etc/letsencrypt/* /etc/letsencrypt-host/"
networks:
  ceasefire-test-backend-dev_alerts:
    external: true
