version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    labels:
      io.portainer.accesscontrol.teams: /certh
    ports:
      - "80:80"    # Changed from 5173 for HTTP
      - "443:443"  # Added HTTPS port
    restart: unless-stopped
    volumes:
      - ./distVDockerHarbor:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt  # Added for SSL certificates
      - ./certbot/www:/var/www/certbot   # Added for ACME challenges
    networks:
      - alerts
    command: >
      sh -c "nginx -g 'daemon off;' & while :; do sleep 6h; nginx -s reload; done"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx:/etc/nginx/conf.d  # Share nginx config
    networks:
      - alerts
    depends_on:
      - nginx
    command: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email kostisfl@iti.gr
      -d cyberpatrol-pilots.ceasefire-project.eu
      -d www.cyberpatrol-pilots.ceasefire-project.eu
      --agree-tos --non-interactive --keep-until-expiring
      && cp /etc/letsencrypt/options-ssl-nginx.conf /etc/nginx/conf.d/
      && cp /etc/letsencrypt/ssl-dhparams.pem /etc/nginx/conf.d/
      && trap exit TERM; while :; do certbot renew; sleep 12h; done"

networks:
  alerts:
    driver: bridge

volumes:
  postgres: