services:
  nginx-ssl:
    container_name: nginx-ssl
    image: nginx:latest
    ports: 
      - "80:80"
    volumes:
      - ./nginx/templates-initiate:/etc/nginx/templates
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/cerbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx-ssl
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email kostisfl@iti.gr --agree-tos --no-eff-email
             -d cyberpatrol-pilots.ceasefire-project.eu www.cyberpatrol-pilots.ceasefire-project.eu
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot